all:*.cpp
	g++ -O3 -Wall CochlearModel_1D_fft.cpp -o CochlearModel_1D_fft -I/usr/local/include -L/usr/local/lib -lfftw3 -lm -I/usr/local/OpenBLAS/include/openblas -L/usr/local/OpenBLAS/lib -lopenblas -lpthread -llapack

